### ISSUE TITLE
‘’vue-pano'引入报错

### ISSUE THREAD

**Issue by vmto** [ChiChou/vue-pano#1]
import Pano from ‘’vue-pano'; 
这样引入报错：
vue.esm.js?65d7:479 [Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <Pano>
       <-User> at demo\src\page\User.vue
           <-App> at demo\src\App.vue
             <-Root>

用以下方式是可以的：
import Pano from '../node_modules/vue-pano/src/Pano.vue';

**Comment by ChiChou** [comment]
感谢反馈，我有空分析一下

**Comment by ChiChou** [comment]
抱歉之前的文档有误，在之前的版本中应该使用 import { Pano } from 'vue-pano'

现在已经将 main 入口更换，升级版本至 1.3.2 即可

**Comment by vmto** [comment]
yarn、npm的1.3.2版本 ，node_modules\vue-pano目录下没有找到index.js文件 ...
并且，如果不看源码，很少人知道也要主动依赖这个包：es6-promise

**Comment by ChiChou** [comment]
入口不是 index.js，而是 dist/ 里打包好的生成文件。这个打包除去了 vue 的运行时，但 es6-promise 是打包进去了的，不需要主动依赖。

我用空白项目测试了一下，1.3.4 应该是彻底修复了。

**Comment by ChiChou** [comment]
发布的 bug 有点多，非常抱歉~

**Comment by vmto** [comment]
vue-pano 1.3.4 是一个振奋人心的版本^_^
