### ISSUE TITLE
您好，关于您写的demo我看到了，非常棒，我也想参考您的代码，可是有点问题需要咨询您。

### ISSUE THREAD

**Issue by liu-zhao** [ChiChou/vue-pano#5]
是这样的，我这边是个vue的移动端项目，然后需要增加全景模块，我参考了您代码的内容，但是在vue页面中引用pano这个标签的时候提示没有正确的注册组建，无法识别，并且还提示没有加载three.min.js 等，我看您的项目中并没有添加这两个js，我想问下您这个应该怎么解决？

**Comment by liu-zhao** [comment]
![image](https://user-images.githubusercontent.com/16305212/45077063-b6465d00-b11e-11e8-95a8-33c3be05b962.png)
![image](https://user-images.githubusercontent.com/16305212/45077076-c1998880-b11e-11e8-938c-02a67788d09c.png)
![image](https://user-images.githubusercontent.com/16305212/45077083-cb22f080-b11e-11e8-86b6-e7beea9e0882.png)

**Comment by ChiChou** [comment]
对不起，photo-sphere-viewer.min.js 与本项目完全没有关系，请自行移步
https://github.com/JeremyHeleine/Photo-Sphere-Viewer

**Comment by ChiChou** [comment]
从 npm 导入的包请使用如下写法：
`import Pano from 'vue-pano'`

你需要巩固一下 vue 的知识
